version: '2'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
  app:
    build:
      context: ./inspire-front
      dockerfile: Dockerfile
    container_name: inspire-front
    working_dir: /var/www/app
    volumes:
      - ./inspire-front:/var/www/app
    ports:
      - "$DEBUG_PORT:$DEBUG_PORT"
    environment:
      - NODE_ENV=$NODE_ENV
      - PORT=$APP_PORT
      - DEBUG_PORT=$DEBUG_PORT
    command: yarn dev
  api:
     build:
       context: ./backend
       dockerfile: Dockerfile
     container_name: inspire-api
     command: python manage.py runserver 0.0.0.0:$API_PORT
     working_dir: /code
     volumes:
       - ./backend:/code
  elastic:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    environment:
      - discovery.type=single-node
    container_name: search_elastic
    volumes:
      - inspire-elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  inspire-elastic-data:
    driver: local
